# Generated by Django 4.0 on 2021-12-22 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('method', '0002_alter_methodabilityprice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityControlPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, max_length=8, null=True, verbose_name='序号')),
                ('qc_tools', models.SmallIntegerField(blank=True, choices=[(0, '能力验证'), (1, '数理统计'), (2, '使用标准物质'), (3, '实验室间比对'), (4, '仪器比对'), (5, '方法比对'), (6, '人员比对'), (7, '留样再测'), (8, '不同检测结果的相关性')], default=1, null=True, verbose_name='质控手段')),
                ('frequency', models.CharField(choices=[('daily', '日检'), ('weekly', '周检'), ('monthly', '月检'), ('quarterly', '季检'), ('half a year', '半年检'), ('yearly', '年检'), ('each batch', '每批次'), ('others', '其他')], default='each batch', max_length=12, verbose_name='频次要求')),
                ('date', models.DateField(auto_now_add=True, verbose_name='更新日期')),
                ('location_code', models.CharField(default='CS', max_length=8)),
                ('equipment', models.CharField(blank=True, max_length=36, null=True, verbose_name='设备')),
                ('group', models.CharField(blank=True, max_length=24, null=True, verbose_name='组别')),
                ('state', models.SmallIntegerField(default=7, verbose_name='质控评分')),
                ('is_controlled', models.BooleanField(default=True, help_text='不在控制中或者失效时用来代替删除', verbose_name='质控中')),
                ('controlled_by', models.ForeignKey(limit_choices_to={'general_staff_list__tags': 'technical'}, on_delete=django.db.models.deletion.CASCADE, related_name='quality_control_plan', to='auth.user', verbose_name='项目负责人')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_control_plan', to='method.methodabilityprice', verbose_name='质控项目')),
            ],
            options={
                'verbose_name': '质控计划',
                'verbose_name_plural': '质控计划',
                'ordering': ['serial_no'],
            },
        ),
    ]
