# Generated by Django 4.0 on 2021-12-22 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(blank=True, max_length=36, null=True, verbose_name='文件编号')),
                ('title', models.CharField(blank=True, max_length=36, null=True, verbose_name='文件名称')),
                ('category', models.CharField(choices=[('质量手册', '质量手册'), ('程序文件', '程序文件'), ('作业指导书', '作业指导书'), ('质量记录表格', '质量记录表格')], default='作业指导书', max_length=36, verbose_name='文件类别')),
                ('tags', models.CharField(blank=True, max_length=24, null=True, verbose_name='标签')),
                ('version', models.CharField(blank=True, max_length=12, null=True, verbose_name='版次')),
                ('editor', models.CharField(blank=True, max_length=12, null=True, verbose_name='编写')),
                ('checked_by', models.CharField(blank=True, max_length=12, null=True, verbose_name='审核')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='颁布日期')),
                ('changed_date', models.DateField(blank=True, null=True, verbose_name='修改日期')),
                ('status', models.CharField(choices=[('controlled', '受控'), ('uncontrolled', '非受控')], default='uncontrolled', max_length=16, verbose_name='受控状态')),
                ('upload', models.FileField(blank=True, null=True, upload_to='quality_document/', verbose_name='在线资源')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_issued', to='auth.user', verbose_name='批准')),
            ],
            options={
                'verbose_name': '质量体系文件管理',
                'verbose_name_plural': '质量体系文件管理',
                'db_table': 'quality_document',
                'unique_together': {('file_no', 'version')},
            },
        ),
    ]
