# Generated by Django 4.0 on 2021-12-20 05:25

import adminpro.fields.sample
import adminpro.utils.common
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=12, null=True, verbose_name='分地点代码')),
                ('sample_no', models.CharField(blank=True, help_text='系统自动创建: 月份(2位)+流水号+随机字符(1~2位)+分地点代码(2~3位)+年代号后2位,总计12位', max_length=18, null=True, verbose_name='样品编号')),
                ('report_no', models.CharField(blank=True, max_length=24, null=True, verbose_name='报告编号')),
                ('order_no', models.CharField(blank=True, max_length=24, null=True, verbose_name='委托单号')),
                ('name', models.CharField(blank=True, max_length=48, null=True, verbose_name='样品名称')),
                ('client', models.CharField(blank=True, max_length=128, null=True, verbose_name='委托单位')),
                ('sampling', models.DateField(blank=True, null=True, verbose_name='取样日期')),
                ('reception', models.DateField(default=django.utils.timezone.now, verbose_name='接收日期')),
                ('time', models.TimeField(default=django.utils.timezone.now, null=True, verbose_name='接收时间')),
                ('description', models.CharField(blank=True, help_text='外观,标识信息等...', max_length=256, null=True, verbose_name='状态描述')),
                ('grade', models.CharField(blank=True, max_length=32, null=True, verbose_name='样品规格')),
                ('register', models.CharField(blank=True, max_length=32, null=True, verbose_name='收样人')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('sub_fee', models.FloatField(blank=True, default=0, null=True, verbose_name='分包费')),
                ('delivery_fee', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='送样费')),
                ('is_checked', models.BooleanField(default=False, verbose_name='复核')),
                ('report', adminpro.fields.sample.RestrictedFileField(blank=True, help_text='请以PDF或ZIP格式上传', null=True, upload_to=adminpro.utils.common.upload_direct_path, verbose_name='测试报告')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_logbook', to='auth.user')),
            ],
            options={
                'verbose_name': '样品管理',
                'verbose_name_plural': '样品管理',
                'db_table': 'sample_log',
            },
        ),
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=32, null=True, verbose_name='检测项目')),
                ('method', models.CharField(blank=True, max_length=64, null=True, verbose_name='测试方法')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='检测日期')),
                ('completed', models.DateField(auto_now_add=True, null=True, verbose_name='结束日期')),
                ('type', models.SmallIntegerField(choices=[(1, '正常业务'), (0, '分包'), (2, '质控')], default=1, verbose_name='测试类型')),
                ('result', models.CharField(blank=True, max_length=64, null=True, verbose_name='结果')),
                ('unit', models.CharField(blank=True, default='-', max_length=32, null=True)),
                ('spec', models.CharField(blank=True, max_length=64, null=True)),
                ('chemist', models.CharField(blank=True, help_text='分包项目可用“分包”代替', max_length=6, null=True, verbose_name='检测人员')),
                ('score', models.DecimalField(decimal_places=1, default=1.0, help_text='计件制用来计算员工工作量的数据', max_digits=2, verbose_name='绩效分')),
                ('allowance', models.PositiveIntegerField(default=5, help_text='计件制用来计算员工绩效补贴的数据,默认为5元')),
                ('is_kpi', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否计入KPI,选择否将不计入绩效')),
                ('is_display', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否显示,代替硬删除')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_logbook', to='sample.samplelog', verbose_name='样品信息')),
            ],
            options={
                'verbose_name': '测试管理',
                'verbose_name_plural': '测试管理',
                'db_table': 'test_log',
            },
        ),
    ]
