# Generated by Django 4.0 on 2021-12-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('method', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodabilityprice',
            options={'verbose_name': '方法价目表', 'verbose_name_plural': '方法价目表'},
        ),
        migrations.RemoveField(
            model_name='methodabilityprice',
            name='remark',
        ),
        migrations.AlterField(
            model_name='methodabilityprice',
            name='validation',
            field=models.CharField(choices=[('validated', '具备能力'), ('NA', '不具备')], default='validated', max_length=12),
        ),
        migrations.AlterModelTable(
            name='methodabilityprice',
            table='method_price',
        ),
    ]
