# Generated by Django 4.0 on 2021-12-22 08:34

import adminpro.utils.common
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('equipment', '0001_initial'),
        ('method', '0002_alter_methodabilityprice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='CS', max_length=5, verbose_name='分地点代码')),
                ('date', models.DateField(verbose_name='完成日期')),
                ('equip_std_info', models.CharField(blank=True, max_length=512, null=True, verbose_name='设备/标准物质编号')),
                ('validated_by', models.CharField(max_length=24, null=True, verbose_name='开发人')),
                ('upload', models.FileField(blank=True, null=True, upload_to=adminpro.utils.common.upload_direct_path, verbose_name='验证资料')),
                ('approved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='method_validation', to='auth.user', verbose_name='开发人')),
                ('equip_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='method_validation', to='equipment.equipmentlist', verbose_name='设备信息')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='method_validation', to='method.methodabilityprice')),
            ],
            options={
                'verbose_name': '方法验证',
                'verbose_name_plural': '方法验证',
                'db_table': 'method_validation',
            },
        ),
    ]
