# Generated by Django 4.0 on 2021-12-20 07:37

import adminpro.utils.common
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备名称')),
                ('location', models.CharField(blank=True, max_length=12, null=True, verbose_name='分地点代码')),
                ('lab_sn', models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='设备编号')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='型号')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True, verbose_name='生产厂家')),
                ('manufacturer_sn', models.CharField(blank=True, max_length=32, null=True, verbose_name='出厂编号')),
                ('measure_range', models.CharField(blank=True, max_length=128, null=True, verbose_name='测量范围')),
                ('status', models.CharField(choices=[('normal service', '正常使用'), ('out of service', '停用'), ('degradation', '降级使用'), ('in repairing', '故障待修'), ('scrapped', '报废'), ('others', '其他')], default='normal service', max_length=16, verbose_name='设备状态')),
                ('purchased_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='采购价格')),
                ('asset_acq_way', models.CharField(choices=[('自有', '自有'), ('租赁', '租赁')], default='自有', max_length=12, verbose_name='资产取得方式')),
                ('power', models.SmallIntegerField(blank=True, null=True, verbose_name='功率(w)')),
                ('validation', models.FileField(blank=True, null=True, upload_to='equipment/validation/', verbose_name='验收资料上传')),
                ('category', models.CharField(choices=[('关键设备', '关键设备'), ('辅助设备', '辅助设备'), ('计量器具', '计量器具')], default='关键设备', max_length=12, verbose_name='分类')),
                ('picture', models.ImageField(blank=True, max_length=128, null=True, upload_to=adminpro.utils.common.upload_direct_path, verbose_name='设备图片')),
                ('first_duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_first', to='auth.user', verbose_name='设备员')),
            ],
            options={
                'verbose_name': '设备总表',
                'verbose_name_plural': '设备总表',
                'db_table': 'equipment_list',
            },
        ),
    ]
