# Generated by Django 4.0 on 2021-12-22 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralStaffList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='姓名')),
                ('staff_id', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='工号')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('identity_no', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='身份号')),
                ('qualification', models.CharField(blank=True, max_length=8, null=True, verbose_name='职称')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('degree', models.CharField(blank=True, max_length=16, null=True, verbose_name='文化程度')),
                ('major', models.CharField(blank=True, max_length=16, null=True, verbose_name='所学专业')),
                ('graduated_time', models.DateField(blank=True, null=True, verbose_name='毕业时间')),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('years_post', models.SmallIntegerField(blank=True, null=True, verbose_name='本岗位年限')),
                ('remark', models.CharField(blank=True, max_length=16, null=True, verbose_name='备注')),
                ('region', models.CharField(blank=True, max_length=8, null=True, verbose_name='地区')),
                ('resign_date', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('tags', models.CharField(blank=True, choices=[('management', '管理人员'), ('technical', '技术人员'), ('sales', '销售'), ('admin', '办公室人员'), ('others', '合作伙伴')], max_length=12, null=True)),
                ('certificate_sn', models.CharField(blank=True, max_length=12, null=True, verbose_name='岗位资格证书编号')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='hr/certificate/', verbose_name='岗位资格证书')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_class_staffs', to='manpower.generalstafflist', verbose_name='上级主管')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='general_staff_list', to='auth.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '人员总表',
                'verbose_name_plural': '人员总表',
            },
        ),
    ]
